"""Find failure cases in the real results and write results/error_cases.md.

    python analyze_errors.py

Retrieval cases need no key. Answer cases (false refusals, answers to out-of-scope questions, invalid
citations, low judge scores) are added when evaluation/answers.json exists. research/error_analysis.md
discusses these cases.
"""
import json
import os

from evaluation.metrics import is_relevant
from retrieve import get_retriever

METHODS = ["dense", "bm25", "hybrid", "hybrid_rerank"]
SHORT = {"dense": "dense", "bm25": "bm25", "hybrid": "hybrid", "hybrid_rerank": "rerank"}


def first_rank(found, q):
    for i, c in enumerate(found, start=1):
        if is_relevant(c, q):
            return i
    return None


def fmt(rank):
    return str(rank) if rank else "miss"


def table(rows, title, note):
    lines = [f"## {title}", note, ""]
    if not rows:
        return lines + ["_No cases._", ""]
    lines += ["| Question | Category | Section | " + " | ".join(SHORT[m] for m in METHODS) + " |",
              "|---|---|---|" + "---|" * len(METHODS)]
    for q, ranks in rows:
        lines.append(f"| {q['question_id']}: {q['question'][:70]} | {q['category']} | {q['source_section']} | "
                     + " | ".join(fmt(ranks[m]) for m in METHODS) + " |")
    return lines + [""]


def main():
    retriever = get_retriever()
    cfg = retriever.cfg
    questions = json.load(open(cfg["questions_file"], encoding="utf-8"))
    answerable = [q for q in questions if q["answerable"]]
    ranks = []
    for q in answerable:
        ranks.append((q, {m: first_rank(retriever.retrieve(q["question"], m, cfg["eval_depth"]), q) for m in METHODS}))
    big = 99
    r = lambda d, m: d[m] or big

    out = ["# Error cases (generated by analyze_errors.py from the real results)", "",
           "Numbers are the rank (1 = best) of the first relevant chunk in the top 10; `miss` = not in the top 10.", ""]
    out += table([(q, d) for q, d in ranks if r(d, "bm25") <= 5 < r(d, "dense")],
                 "A. BM25 found the evidence in the top 5, dense did not", "Exact wording helped.")
    out += table([(q, d) for q, d in ranks if r(d, "dense") <= 5 < r(d, "bm25")],
                 "B. Dense found the evidence in the top 5, BM25 did not", "Meaning / paraphrase helped.")
    out += table([(q, d) for q, d in ranks if r(d, "hybrid_rerank") + 2 <= r(d, "hybrid")],
                 "C. Reranking moved the evidence up by 2 or more ranks (vs hybrid)", "")
    out += table([(q, d) for q, d in ranks if r(d, "hybrid_rerank") > r(d, "hybrid")],
                 "D. Reranking moved the evidence down (vs hybrid)", "")
    out += table([(q, d) for q, d in ranks if r(d, "hybrid") > r(d, "dense")],
                 "E. Hybrid ranked the evidence lower than dense", "")
    out += table([(q, d) for q, d in ranks if all(r(d, m) > 5 for m in ("dense", "hybrid", "hybrid_rerank"))],
                 "F. No main method had the evidence in the top 5", "")

    multi = [(q, d) for q, d in ranks if len(q["relevant_sections"]) > 1]
    out += ["## G. Multi-section questions (Recall@5 of the main methods)", ""]
    out += ["| Question | Sections | dense | hybrid | rerank |", "|---|---|---|---|---|"]
    from evaluation.metrics import recall_at_k
    for q, _ in multi:
        rec = {m: recall_at_k(retriever.retrieve(q["question"], m, cfg["eval_depth"]), q, 5)
               for m in ("dense", "hybrid", "hybrid_rerank")}
        out.append(f"| {q['question_id']}: {q['question'][:60]} | {', '.join(q['relevant_sections'])} | "
                   f"{rec['dense']:.2f} | {rec['hybrid']:.2f} | {rec['hybrid_rerank']:.2f} |")
    out.append("")

    path = os.path.join(cfg["evaluation_dir"], "answers.json")
    if os.path.exists(path):
        records = json.load(open(path, encoding="utf-8"))
        by_id = {q["question_id"]: q for q in questions}
        rank_by = {q["question_id"]: d for q, d in ranks}

        def where(rec):
            q = by_id[rec["question_id"]]
            hit = rank_by.get(q["question_id"], {}).get(rec["method"])
            if hit and hit <= cfg["top_k"]:
                return f"evidence was in the context (rank {hit})"
            if hit:
                return f"evidence outside the top {cfg['top_k']} (rank {hit})"
            return "evidence NOT retrieved"

        false_ref = [x for x in records if by_id[x["question_id"]]["answerable"] and x["status"] == "INSUFFICIENT EVIDENCE"]
        out += ["## H. False refusals (answerable question, answer says insufficient evidence)", "",
                "| Question | Method | Retrieval |", "|---|---|---|"]
        for x in sorted(false_ref, key=lambda x: (x["question_id"], x["method"])):
            out.append(f"| {x['question_id']}: {x['question'][:60]} | {x['method']} | {where(x)} |")
        bad_oos = [x for x in records if not by_id[x["question_id"]]["answerable"] and x["status"] != "INSUFFICIENT EVIDENCE"]
        out += ["", "## I. Out-of-scope questions answered instead of refused", "",
                "| Question | Method | Answer (start) |", "|---|---|---|"]
        for x in bad_oos:
            out.append(f"| {x['question_id']}: {x['question'][:50]} | {x['method']} | {x['answer'][:110].replace(chr(10), ' ')} |")
        if not bad_oos:
            out.append("| _none_ | | |")
        from evaluation.metrics import citation_metrics
        invalid = []
        for x in records:
            q = by_id[x["question_id"]]
            if q["answerable"] and x["citations"]:
                m = citation_metrics(x["citations"], x["retrieved_context"], q)
                if m["cite_valid"] < 1:
                    invalid.append((x, m))
        out += ["", "## J. Answers with a citation that does not match a retrieved chunk", "",
                "| Question | Method | cite_valid | cited |", "|---|---|---|---|"]
        for x, m in invalid:
            cited = "; ".join(f"{c['section']}" for c in x["citations"])
            out.append(f"| {x['question_id']} | {x['method']} | {m['cite_valid']:.2f} | {cited} |")
        if not invalid:
            out.append("| _none_ | | | |")
        low = [x for x in records if by_id[x["question_id"]]["answerable"] and x.get("correctness_score") is not None
               and x["correctness_score"] <= 1 and x["status"] != "INSUFFICIENT EVIDENCE"]
        out += ["", "## K. Supported-looking answers that the judge scored 0 or 1 for correctness", "",
                "| Question | Method | scores (corr/faith/rel/cite) | Retrieval | Judge reason |", "|---|---|---|---|---|"]
        for x in sorted(low, key=lambda x: (x["question_id"], x["method"])):
            out.append(f"| {x['question_id']} | {x['method']} | {x['correctness_score']}/{x['faithfulness_score']}/"
                       f"{x['relevance_score']}/{x['citation_score']} | {where(x)} | {x.get('judge_reason', '')[:140]} |")
        if not low:
            out.append("| _none_ | | | | |")
        out.append("")
    else:
        out += ["_Answer cases are pending: evaluation/answers.json does not exist yet._", ""]

    os.makedirs(cfg["results_dir"], exist_ok=True)
    with open(os.path.join(cfg["results_dir"], "error_cases.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print("Saved results/error_cases.md")


if __name__ == "__main__":
    main()
